package org.example;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Pacto4Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","C:\\Users\\blalvare\\OneDrive - Capgemini\\Desktop\\chromedriver\\chromedriver.exe");

    driver = new ChromeDriver();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pacto4() {
    // Test name: pacto4
    // Step # | name | target | value
    // 1 | open | https://cursosdedesarrollo.com/pactometro/ | 
    driver.get("https://cursosdedesarrollo.com/pactometro/");
    // 2 | setWindowSize | 798x824 | 
    driver.manage().window().setSize(new Dimension(798, 824));
    // 3 | click | id=part-PSOE | 
    driver.findElement(By.id("part-PSOE")).click();
    // 4 | click | id=part-Podemos | 
    driver.findElement(By.id("part-Podemos")).click();
    // 5 | click | id=part-ERC | 
    driver.findElement(By.id("part-ERC")).click();
    // 6 | click | id=sies | 
    driver.findElement(By.id("sies")).click();
    // 19 | assertText | id=num-sies | 168
    assertEquals(driver.findElement(By.id("num-sies")).getText(), "168");
    // 7 | click | css=#part-Ciudadanos > img | 
    driver.findElement(By.cssSelector("#part-Ciudadanos > img")).click();
    // 8 | click | id=abst | 
    driver.findElement(By.id("abst")).click();
    assertEquals(driver.findElement(By.id("num-abst")).getText(), "10");
    assertEquals(driver.findElement(By.id("num-noes")).getText(), "0");

    // 20 | click | id=noes | 
    driver.findElement(By.id("noes")).click();
    // 21 | click | id=reset | 
    driver.findElement(By.id("reset")).click();
    assertEquals(driver.findElement(By.id("num-sies")).getText(), "0");
    assertEquals(driver.findElement(By.id("num-abst")).getText(), "0");
    assertEquals(driver.findElement(By.id("num-noes")).getText(), "0");

  }
  @Test
  public void testBotonPulsadoBotonDeshabilitado(){
    // 1 | open | /pactometro/ |
    driver.get("https://cursosdedesarrollo.com/pactometro/");
    // 2 | setWindowSize | 1402x1219 |
    driver.manage().window().setSize(new Dimension(1402, 1219));
    WebElement botonPP = driver.findElement(By.id("part-PP"));
    botonPP.click();
    // System.out.println(botonPP.getAttribute("disabled"));
    assertEquals("true", botonPP.getAttribute("disabled"));
    driver.findElement(By.id("noes")).click();
    botonPP = driver.findElement(By.id("part-PP"));
    // System.out.println("style: " +botonPP.getAttribute("style"));
    assertEquals("display: none;", botonPP.getAttribute("style"));
  }
  @Test
  public void testBotonPulsadoBotonDeshabilitadoPSOE(){
    // 1 | open | /pactometro/ |
    driver.get("https://cursosdedesarrollo.com/pactometro/");
    // 2 | setWindowSize | 1402x1219 |
    driver.manage().window().setSize(new Dimension(1402, 1219));
    WebElement botonPSOE = driver.findElement(By.id("part-PSOE"));
    botonPSOE.click();
    // System.out.println(botonPP.getAttribute("disabled"));
    assertEquals("true", botonPSOE.getAttribute("disabled"));
    driver.findElement(By.id("noes")).click();
    botonPSOE = driver.findElement(By.id("part-PSOE"));
    // System.out.println("style: " +botonPP.getAttribute("style"));
    assertEquals("display: none;", botonPSOE.getAttribute("style"));
  }
}
