package org.example;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

import static org.junit.jupiter.api.Assertions.assertEquals;


public class Wiki4Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","C:\\Users\\blalvare\\OneDrive - Capgemini\\Desktop\\chromedriver\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void wiki4() {
    // Test name: wiki4
    // Step # | name | target | value
    // 1 | open | /wiki/Main_Page | 
    driver.get("https://en.wikipedia.org/wiki/Main_Page");
    // 2 | setWindowSize | 794x824 | 
    driver.manage().window().setSize(new Dimension(794, 824));
    // 3 | click | id=searchInput | 
    driver.findElement(By.id("searchInput")).click();
    // 4 | type | id=searchInput | europe
    driver.findElement(By.id("searchInput")).sendKeys("europe");
    // 5 | click | id=searchButton | 
    driver.findElement(By.id("searchButton")).click();
    // 6 | click | css=p:nth-child(7) | 
    driver.findElement(By.cssSelector("p:nth-child(7)")).click();
    // 7 | assertText | css=p:nth-child(7) | Europe is a landmass conventionally considered a continent in its own right because of its great physical size and the weight of its history and traditions. Europe is also a subcontinent of Eurasia and it's located entirely in the Northern Hemisphere and mostly in the Eastern Hemisphere. Comprising the westernmost peninsulas of Eurasia,[10] it shares the continental landmass of Afro-Eurasia with both Africa and Asia. It is bordered by the Arctic Ocean to the north, the Atlantic Ocean to the west, the Mediterranean Sea to the south and Asia to the east. Europe is commonly considered to be separated from Asia by the watershed of the Ural Mountains, the Ural River, the Caspian Sea, the Greater Caucasus, the Black Sea and the waterways of the Turkish Straits.[11]
    assertEquals(driver.findElement(By.cssSelector("p:nth-child(7)")).getText(), "Europe is a landmass conventionally considered a continent in its own right because of its great physical size and the weight of its history and traditions. Europe is also a subcontinent of Eurasia and it's located entirely in the Northern Hemisphere and mostly in the Eastern Hemisphere. Comprising the westernmost peninsulas of Eurasia,[10] it shares the continental landmass of Afro-Eurasia with both Africa and Asia. It is bordered by the Arctic Ocean to the north, the Atlantic Ocean to the west, the Mediterranean Sea to the south and Asia to the east. Europe is commonly considered to be separated from Asia by the watershed of the Ural Mountains, the Ural River, the Caspian Sea, the Greater Caucasus, the Black Sea and the waterways of the Turkish Straits.[11]");

    // 8 | click | css=p:nth-child(7) | 
    driver.findElement(By.cssSelector("p:nth-child(7)")).click();
    // 9 | click | linkText=Atlantic Ocean | 
    driver.findElement(By.linkText("Atlantic Ocean")).click();
  }
}
